modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "optimized_fullbright"
version = "${version}"
displayName = "Optimized Fullbright"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.optimized_fullbright]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.optimized_fullbright]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"
