modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "optimizedfullbright"
version = "${version}"
displayName = "Optimized Fullbright"
authors = "ray"
description = '''
Fullbright mod that disables the lighting system to improve performance.
'''
#logoFile = ""

[[dependencies.optimizedfullbright]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.optimizedfullbright]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21.11]"
ordering = "NONE"
side = "BOTH"
