modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "optimizedfullbright"
version = "${version}"
displayName = "Optimized Fullbright"
authors = "ray"
description = '''
Fullbright mod that disables the lighting system to improve performance.
'''
#logoFile = ""

[[dependencies.optimizedfullbright]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.optimizedfullbright]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,1.21.11]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "optimized_fullbright.mixins.json"
