#Early window height
earlyWindowHeight = 480
#Enable NeoForge global version checking
versionCheck = true
#Shows an early loading screen for mod loading which improves the user experience with early feedback about mod loading.
earlyWindowControl = true
#Disables File Watcher. Used to automatically update config if its file has been modified.
disableConfigWatcher = false
#Early window provider
earlyWindowProvider = "fmlearlywindow"
#Early window width
earlyWindowWidth = 854
#Early window starts maximized
earlyWindowMaximized = false
#Default config path for servers
defaultConfigPath = "defaultconfigs"
#Disables Optimized DFU client-side - already disabled on servers
disableOptimizedDFU = true
#Max threads for early initialization parallelism,  -1 is based on processor count
maxThreads = -1
#Enable synchronous OpenGL debug output and object labeling
debugOpenGl = false
#Force a given theme-id to be used for the early loading screen
earlyLoadingScreenTheme = ""
